export const SECRET_MASK = '••••••••';

export const SECTION_KEYS = [
  'general',
  'branding',
  'email',
  'billing',
  'security',
  'features',
  'integrations',
  'defaults',
  'maintenance',
] as const;

export type SettingsSectionKey = (typeof SECTION_KEYS)[number];

export const DEFAULT_RESERVED_SLUGS = [
  'www', 'app', 'api', 'admin', 'superadmin', 'mail', 'smtp', 'ftp',
  'blog', 'help', 'support', 'billing', 'status',
];

export function sectionDefaults(): Record<SettingsSectionKey, Record<string, unknown>> {
  return {
    general: {
      platformTagline: 'Restaurant OS for Pakistan',
      whatsappSupport: '',
      websiteUrl: '',
      appDomain: 'yourapp.com',
      superAdminPanelUrl: 'app.yourapp.com',
      defaultLanguage: 'en',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12-hour',
      autoVerifyTenants: false,
      gracePeriodDays: 3,
      reservedSlugs: [...DEFAULT_RESERVED_SLUGS],
      minSlugLength: 3,
      maxSlugLength: 50,
    },
    branding: {
      panelLogoUrl: '',
      panelFaviconUrl: '',
      panelPrimaryColor: '#FA4A0C',
      panelSecondaryColor: '#2D2D2D',
      defaultTenantLogoUrl: '',
      defaultTenantPrimaryColor: '#FF5733',
      defaultTenantSecondaryColor: '#2C3E50',
      defaultFont: 'Inter',
      poweredByText: 'Powered by RestoHub',
      showPoweredBy: true,
      poweredByLogoUrl: '',
      privacyPolicyUrl: '',
      termsUrl: '',
    },
    email: {
      smtpProvider: 'sendgrid',
      smtpHost: '',
      smtpPort: 587,
      smtpUsername: '',
      smtpPassword: '',
      smtpEncryption: 'TLS',
      fromName: 'RestoHub Team',
      fromEmail: 'noreply@yourapp.com',
      replyToEmail: 'support@yourapp.com',
      triggers: {
        newTenantSignedUp: true,
        trialExpiring3Days: true,
        trialExpired: true,
        paymentFailed: true,
        subscriptionRenewed: true,
        tenantSuspended: true,
        supportTicketHigh: true,
        supportTicketUnresolved24h: true,
        tenantNearOrderLimit: true,
        planChanged: true,
      },
      pushNotifications: true,
      notificationSound: true,
      alertEmail: '',
    },
    billing: {
      gateway: 'manual',
      gatewayMode: 'test',
      stripePublishableKey: '',
      stripeSecretKey: '',
      stripeWebhookSecret: '',
      rozarpayKeyId: '',
      rozarpayKeySecret: '',
      bankName: '',
      accountTitle: '',
      accountNumber: '',
      iban: '',
      paymentInstructions: '',
      taxPercent: 0,
      invoicePrefix: 'INV-',
      invoiceStartNumber: 1000,
      autoRetryFailed: true,
      retryAttempts: 3,
      retryIntervalDays: 3,
      dunningDay1: true,
      dunningDay3: true,
      dunningDay7: true,
      dunningDay10Action: 'suspend',
    },
    security: {
      minPasswordLength: 8,
      requireUppercase: true,
      requireNumbers: true,
      requireSpecialChars: false,
      passwordExpiryDays: 0,
      jwtAccessMinutes: 15,
      jwtRefreshDays: 7,
      maxActiveSessions: 3,
      forceLogoutHours: 8,
      require2faRoles: ['SUPER_ADMIN'],
      twoFaMethod: 'authenticator',
      maxLoginAttempts: 5,
      lockoutMinutes: 15,
      ipWhitelist: [] as string[],
      logAllLogins: true,
      alertOnNewIp: true,
      allowImpersonation: true,
      impersonationExpiryMinutes: 15,
      logImpersonation: true,
      notifyTenantOnImpersonation: false,
    },
    features: {
      dineIn: { enabled: true, planRestriction: '' },
      delivery: { enabled: true, planRestriction: '' },
      takeaway: { enabled: true, planRestriction: '' },
      driveThrough: { enabled: false, planRestriction: '' },
      kitchenDisplay: { enabled: true, planRestriction: '' },
      autoAcceptDineIn: { enabled: false, planRestriction: '' },
      tableQrOrdering: { enabled: true, planRestriction: '' },
      waiterTablet: { enabled: true, planRestriction: '' },
      riderApp: { enabled: false, planRestriction: '' },
      riderLocationTrack: { enabled: false, planRestriction: '' },
      pickupRadiusM: 100,
      deliveryRadiusM: 200,
      onlinePayments: { enabled: true, planRestriction: '' },
      splitPayments: { enabled: true, planRestriction: '' },
      cod: { enabled: true, planRestriction: '' },
      partialPayments: { enabled: false, planRestriction: '' },
      customerApp: { enabled: true, planRestriction: '' },
      orderTracking: { enabled: true, planRestriction: '' },
      reviews: { enabled: true, planRestriction: '' },
      loyalty: { enabled: false, planRestriction: '' },
      basicReports: { enabled: true, planRestriction: '' },
      advancedAnalytics: { enabled: false, planRestriction: '' },
      exportCsv: { enabled: true, planRestriction: '' },
      whiteLabel: { enabled: false, planRestriction: '' },
      customDomain: { enabled: false, planRestriction: '' },
      apiAccess: { enabled: false, planRestriction: '' },
      fbrIntegration: { enabled: false, planRestriction: '' },
      offlineMode: { enabled: false, planRestriction: '' },
    },
    integrations: {
      fbrEnabled: false,
      fbrApiEndpoint: '',
      fbrApiKey: '',
      fbrEnvironment: 'test',
      praEnabled: false,
      praApiEndpoint: '',
      praApiKey: '',
      srbEnabled: false,
      kpraEnabled: false,
      googleMapsApiKey: '',
      mapsDefaultRegion: 'PK',
      distanceUnit: 'km',
      fcmServerKey: '',
      twilioEnabled: false,
      twilioAccountSid: '',
      twilioAuthToken: '',
      twilioFromNumber: '',
      storageProvider: 'local',
      awsAccessKeyId: '',
      awsSecretAccessKey: '',
      awsBucket: '',
      awsRegion: 'ap-south-1',
      googleAnalyticsId: '',
      sentryDsn: '',
      logrocketProjectId: '',
    },
    defaults: {
      defaultTaxRate: 5,
      defaultServiceCharge: 10,
      defaultDeliveryFee: 150,
      freeDeliveryAbove: 1500,
      minOrderAmount: 200,
      orderNumberPrefix: 'ORD',
      orderAutoCancelMinutes: 0,
      defaultPrepTime: 20,
      kitchenAutoAccept: false,
      maxItemsPerOrder: 0,
      newOrderSound: 'chime',
      orderAlertVolume: 80,
      billHeader: '',
      billFooter: 'Thank you for dining with us',
      showLogoOnBill: true,
      showTaxBreakdown: true,
      showWaiterName: true,
      showTableNumber: true,
      receiptPaperWidth: '80mm',
    },
    maintenance: {
      maintenanceMessage: 'We are performing scheduled maintenance. Please check back soon.',
      estimatedDuration: '',
      allowedIps: [] as string[],
      scheduleEnableAt: '',
      scheduleDisableAt: '',
    },
  };
}

export const SECRET_FIELDS: Record<string, string[]> = {
  email: ['smtpPassword'],
  billing: ['stripeSecretKey', 'stripeWebhookSecret', 'rozarpayKeySecret'],
  integrations: ['fbrApiKey', 'praApiKey', 'googleMapsApiKey', 'fcmServerKey', 'twilioAuthToken', 'awsSecretAccessKey'],
};
